package com.esteirahabitacional.identityaccess.domain.model;

public enum Permission {
    CREATE_ORGANIZATION,
    MANAGE_INTERNAL_USERS,
    MANAGE_PARTIES,
    VIEW_PARTIES,
    MANAGE_PROCESSES,
    VIEW_PROCESSES,
    MANAGE_DOCUMENTS,
    VIEW_DOCUMENTS,
    AUTHORIZE_WORKFLOW_EXCEPTION,
    VIEW_CURRENT_CONTEXT
}
